version: '3'

services:
  backend:
    container_name: backend
    build: 
      context: backend
      dockerfile: Dockerfile
    image: backend
    restart: always
    env_file: .env
    ports:
      - '4000:3001'
    depends_on:
      - postgres
    networks:
      - backend
      - frontend

  frontend:
    container_name: frontend
    build: 
      context: frontend
      dockerfile: Dockerfile
    image: frontend
    restart: always
    ports:
      - '8081:80'
    networks:
      - frontend
      
  postgres:
    container_name: postgres
    image: postgres:12
    env_file: .env
    volumes:
      - postgres_data:/data/postgres
    restart: always
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
  frontend: